# this might not be necesary (might be root)
#sudo: required

language: cpp

os:
- linux

# default is xenial
dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-7
      - g++-7

### how to install these (and maybe cache for a faster build?)
# some (many?) my already be available
before_install:
  - sudo apt-get update
  - sudo apt-get install -y autotools-dev
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y automake
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libtool
  - sudo apt-get install -y liblapack-dev
  - sudo apt-get install -y libatlas-cpp-0.6-dev
  - sudo apt-get install -y libnlopt-dev
  - sudo apt-get install -y libnlopt0
  - sudo apt-get install -y libarmadillo-dev

# should we include autoconf too?
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cd src && autoreconf -fi && ./configure && make -j 2 && make test

