name: Build-N-Test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Install brew dependencies
      if: runner.os == 'macOS'
      run:
          brew install nlopt armadillo
    - name: Install apt dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install autotools-dev autoconf automake libtool liblapack-dev libatlas-cpp-0.6-dev libnlopt0 libnlopt-dev libarmadillo-dev
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure
    - name: make
      run: make -j
    - name: make check
      run: make check
    - name: make installcheck
      run: make installcheck
