name: Build-N-Test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v4
    - name: Install brew dependencies
      if: runner.os == 'macOS'
      run: |
          # install dependencies
          brew install nlopt armadillo automake autoconf
          # add paths (new brew install location)
          echo "LDFLAGS=-L$(brew --prefix)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix)/include" >> $GITHUB_ENV
    - name: Install apt dependencies
      if: runner.os == 'Linux'
      run: |
        # Ensure the script doesnt hang waiting for user input
          export DEBIAN_FRONTEND=noninteractive
        # Update system
        sudo apt-get update
        sudo apt-get install -y \
        autotools-dev \
        automake \
        libtool \
        liblapack-dev \
        libatlas-base-dev \
        libnlopt0 \
        libnlopt-dev \
        libnlopt-cxx-dev \
        libarmadillo-dev
    - name: autoconf
      run: autoreconf -fiv
    - name: configure
      run: ./configure
    - name: make
      run: make -j
    - name: make check
      run: make check
    - name: make installcheck
      run: make installcheck
